name: Metrics
on:
  # Автоматический запуск каждые 12 часов
  schedule:
    - cron: "0 */12 * * *"
  # Возможность запускать вручную из вкладки Actions
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Токен, который вы сохранили в Secrets под именем METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}

          # Ваш логин
          user: Void-404X
          template: classic
          base: header, activity, community, repositories, metadata

          # Дополнительные фичи (по желанию можно убрать/добавить)
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_achievements: yes
